const AST_OBJECT_TYPES = {
    ARRAY_EXPRESSION: "ArrayExpression",
    ARROW_FUNCTION_EXPRESSION: "ArrowFunctionExpression",
    ASSIGNMENT_EXPRESSION: "AssignmentExpression",
    ASSIGNMENT_PATTERN: "AssignmentPattern",
    BINARY_EXPRESSION: "BinaryExpression",
    BREAK_STATEMENT: "BreakStatement",
    BLOCK_STATEMENT: "BlockStatement",
    CALL_EXPRESSION: "CallExpression",
    CATCH_CLAUSE: "CatchClause",
    CONTINUE_STATEMENT: "ContinueStatement",
    CONDITIONAL_EXPRESSION: "ConditionalExpression",
    DO_WHILE_STATEMENT: "DoWhileStatement",
    EXPRESSION_STATEMENT: "ExpressionStatement",
    FOR_STATEMENT: "ForStatement",
    FOR_OF_STATEMENT: "ForOfStatement",
    FOR_IN_STATEMENT: "ForInStatement",
    FUNCTION_DECLARATION: "FunctionDeclaration",
    FUNCTION_EXPRESSION: "FunctionExpression",
    IDENTIFIER: "Identifier",
    IF_STATEMENT: "IfStatement",
    LITERAL: "Literal",
    LOGICAL_EXPRESSION: "LogicalExpression",
    MEMBER_EXPRESSION: "MemberExpression",
    OBJECT_EXPRESSION: "ObjectExpression",
    RETURN_STATEMENT: "ReturnStatement",
    SWITCH_STATEMENT: "SwitchStatement",
    SWITCH_CASE: "SwitchCase",
    TEMPLATE_LITERAL: "TemplateLiteral",
    TRY_STATEMENT: "TryStatement",
    UNARY_EXPRESSION: "UnaryExpression",
    UPDATE_EXPRESSION: "UpdateExpression",
    VARIABLE_DECLARATION: "VariableDeclaration",
    WHILE_STATEMENT: "WhileStatement",
};

module.exports = Object.freeze(AST_OBJECT_TYPES);
